# Generated by Django 4.2 on 2023-04-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pablo_app", "0002_artist_painting_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="artist",
        ),
        migrations.AddField(
            model_name="genre",
            name="artist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pablo_app.artist",
            ),
            preserve_default=False,
        ),
    ]
