# Generated by Django 4.2 on 2023-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pablo_app", "0003_remove_genre_artist_genre_artist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="painting",
            name="artist",
        ),
        migrations.AddField(
            model_name="artist",
            name="genre",
            field=models.CharField(default="test", max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artist",
            name="paintings",
            field=models.CharField(default="test", max_length=8000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Painting",
        ),
    ]
