# Generated by Django 4.2 on 2023-04-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pablo_app",
            "0004_remove_painting_artist_artist_genre_artist_paintings_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="paintings",
        ),
        migrations.AlterField(
            model_name="artist",
            name="bio",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="artist",
            name="genre",
            field=models.CharField(max_length=400),
        ),
    ]
